services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pandan_app
    restart: always
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - pandan-network

  webserver:
    image: nginx:alpine
    container_name: pandan_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      # Tambahkan 2 baris ini untuk sharing sertifikat SSL
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - pandan-network
    depends_on:
      - app

  # Tambahkan service Certbot ini
  certbot:
    image: certbot/certbot
    container_name: pandan_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  db:
    image: mysql:8.0
    container_name: pandan_db
    restart: always
    environment:
      MYSQL_DATABASE: pandanwangi
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: rootpassword
    volumes:
      - dbdata_prod:/var/lib/mysql
      - ./backup/pandan-backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pandan-network

networks:
  pandan-network:
    driver: bridge

volumes:
  dbdata_prod: